# Generated by Django 2.2.7 on 2019-11-22 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userreview',
            name='avgrating',
            field=models.FloatField(default=0.0),
        ),
    ]
