# Generated by Django 2.2.6 on 2019-11-15 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_email_confirmed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='email_confirmed',
            new_name='is_active',
        ),
    ]
