# Generated by Django 2.2.7 on 2019-11-22 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userreview_avgrating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userreview',
            name='avgrating',
        ),
    ]
