# Generated by Django 2.2.7 on 2019-11-22 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_userreview_avgrating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userreview',
            name='revieweduser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='revieweduser', to='accounts.UserProfile'),
        ),
        migrations.AlterField(
            model_name='userreview',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userreviewing', to='accounts.UserProfile'),
        ),
    ]
