# Generated by Django 2.2.6 on 2019-11-08 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bankdetails',
            old_name='BankHolder',
            new_name='user',
        ),
    ]
