# Generated by Django 2.2.7 on 2019-11-15 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankdetails',
            name='AccountNumber',
            field=models.CharField(max_length=50),
        ),
    ]
