# Generated by Django 2.2.7 on 2019-11-15 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0002_auto_20191116_0238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='TransDate',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
