# Generated by Django 2.2.7 on 2019-11-15 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0003_auto_20191116_0239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='TransDate',
            field=models.DateField(auto_now_add=True),
        ),
    ]
