# Generated by Django 2.2.6 on 2019-11-12 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0003_accountbalance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='balance',
            old_name='balance',
            new_name='accountbalance',
        ),
        migrations.AddField(
            model_name='balance',
            name='availablebalance',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='AccountBalance',
        ),
    ]
