# Generated by Django 2.2.5 on 2019-11-15 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='futurescontract',
            name='AdvanceDate',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
