# Generated by Django 2.2.5 on 2019-12-05 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='futurescontract',
            name='order_status',
            field=models.BooleanField(default=False),
        ),
    ]
