# Generated by Django 2.2.5 on 2019-11-15 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_futurescontract_advancedate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='futurescontract',
            name='AdvanceDate',
            field=models.DateTimeField(null=True),
        ),
    ]
