# Generated by Django 2.2.6 on 2019-11-13 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_futurebid_futuredeal_futurescontract'),
    ]

    operations = [
        migrations.AlterField(
            model_name='futurebid',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='order.FuturesContract'),
        ),
    ]
