# Generated by Django 2.2.7 on 2019-12-06 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_citycrop'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='executedorder',
            name='commision',
        ),
    ]
