# Generated by Django 2.2.5 on 2019-12-07 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_futurescontract_order_status'),
        ('order', '0003_remove_executedorder_commision'),
    ]

    operations = [
    ]
