# Generated by Django 2.2.5 on 2019-11-15 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_auto_20191116_0010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='futurescontract',
            name='AdvanceDate',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='futurescontract',
            name='OrderDate',
            field=models.DateField(auto_now_add=True),
        ),
    ]
