# Generated by Django 2.2.7 on 2019-12-07 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_merge_20191207_1701'),
        ('order', '0004_merge_20191207_1702'),
    ]

    operations = [
    ]
