# Generated by Django 2.2.5 on 2019-11-01 19:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_auto_20191102_0114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bidmid',
            name='bidid',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='order.Bid'),
        ),
        migrations.AlterField(
            model_name='bidmid',
            name='userid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
