# Generated by Django 2.2.7 on 2019-12-08 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_merge_20191207_2357'),
    ]

    operations = [
        migrations.CreateModel(
            name='CropProduction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cropname', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('quantity', models.FloatField(default=0.0)),
            ],
        ),
    ]
