# Generated by Django 2.2.5 on 2019-11-01 20:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order', '0005_auto_20191102_0118'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='userid',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Bidmid',
        ),
    ]
