# Generated by Django 2.2.5 on 2019-11-01 20:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order', '0006_auto_20191102_0133'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='userid',
        ),
        migrations.AddField(
            model_name='bid',
            name='userid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True),
        ),
    ]
