# Generated by Django 2.2.5 on 2019-11-01 20:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order', '0009_auto_20191102_0202'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='price',
            field=models.FloatField(default=None),
        ),
        migrations.CreateModel(
            name='ExecutedOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('commision', models.FloatField(default=None)),
                ('buyerid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('orderid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='order.MarketOrder')),
            ],
        ),
    ]
