# Generated by Django 2.2.6 on 2019-11-02 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_auto_20191102_0222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketorder',
            name='OrderStatus',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3')], max_length=10),
        ),
    ]
