# Generated by Django 2.2.6 on 2019-11-02 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0011_auto_20191103_0147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketorder',
            name='ClosingDate',
            field=models.DateField(),
        ),
    ]
