# Generated by Django 2.2.6 on 2019-11-03 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0013_auto_20191103_0235'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketorder',
            name='OrderName',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
