# Generated by Django 2.2.6 on 2019-11-04 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0014_marketorder_ordername'),
    ]

    operations = [
        migrations.RenameField(
            model_name='marketorder',
            old_name='user',
            new_name='Created_by',
        ),
        migrations.AlterField(
            model_name='marketorder',
            name='OrderName',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
