# Generated by Django 2.2.6 on 2019-11-06 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0016_auto_20191104_2316'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marketorder',
            name='OrderName',
        ),
    ]
