# Generated by Django 2.2.6 on 2019-11-11 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0017_remove_marketorder_ordername'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketorder',
            name='ClosingDate',
            field=models.DateField(),
        ),
    ]
