# Generated by Django 2.2.6 on 2019-11-08 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0018_auto_20191108_0046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketorder',
            name='OrderDate',
            field=models.DateField(auto_now_add=True),
        ),
    ]
