# Generated by Django 2.2.7 on 2019-11-12 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crop',
            name='varietyName',
        ),
        migrations.CreateModel(
            name='CropVariety',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cropvariety', models.CharField(max_length=50)),
                ('cropname', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='crop.Crop')),
            ],
        ),
    ]
