# Generated by Django 2.2.7 on 2019-11-12 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crop', '0002_auto_20191112_2323'),
    ]

    operations = [
        migrations.AddField(
            model_name='crop',
            name='varietyName',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='CropVariety',
        ),
    ]
