# Generated by Django 2.2.7 on 2019-12-05 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crop', '0003_auto_20191204_2156'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pricedata',
            name='closing',
        ),
        migrations.RemoveField(
            model_name='pricedata',
            name='high',
        ),
        migrations.RemoveField(
            model_name='pricedata',
            name='low',
        ),
        migrations.RemoveField(
            model_name='pricedata',
            name='opening',
        ),
        migrations.RemoveField(
            model_name='pricedata',
            name='volume',
        ),
        migrations.AddField(
            model_name='pricedata',
            name='price',
            field=models.FloatField(default=0.0),
        ),
    ]
