# Generated by Django 2.2.7 on 2019-12-05 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crop', '0004_auto_20191205_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricedata',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
