# Generated by Django 2.2.7 on 2019-12-08 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crop', '0007_auto_20191205_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricedata',
            name='timestamp',
            field=models.DateTimeField(),
        ),
    ]
