# Generated by Django 2.2.7 on 2019-12-08 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crop', '0008_auto_20191208_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricedata',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
