# Generated by Django 2.2.5 on 2019-09-18 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='Date',
        ),
        migrations.AddField(
            model_name='order',
            name='random',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
